name: Feature request
description: Suggest an enhancement
title: "[Feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      placeholder: "Describe the problem this solves"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: "High-level approach"
  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance criteria
      options:
        - label: Tests planned
        - label: Security implications considered
